### ISSUE TITLE
Bundler.require :defaultって？Gemfileがないところで動かない？

### ISSUE THREAD

**Issue by DoG-peer** [plonk/bbiff#8]
Gemfileのないディレクトリでbbiffを実行すると、

```
/home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:163:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:159:in `root'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:71:in `bundle_path'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:419:in `configure_gem_home'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:407:in `configure_gem_home_and_path'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:57:in `configure'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:118:in `definition'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:88:in `setup'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bbiff-0.1.2/lib/bbiff.rb:2:in `<top (required)>'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bbiff-0.1.2/bin/bbiff:5:in `<top (required)>'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/bin/bbiff:23:in `load'
        from /home/user/.anyenv/envs/rbenv/versions/2.3.0/bin/bbiff:23:in `<main>'
```

のようなエラーが出ます。空のGemfileがあるだけだと、読み込むべきものが読み込まれないので、ローカルのbbiffディレクトリでないと実行できない。

**Comment by plonk** [comment]
91100fb40ad1961b40a0f262c7ad1ac4870399d8 で修正しました。

**Comment by DoG-peer** [comment]
ありがとう
